[error] sbt.librarymanagement.ResolveException: Error downloading org.datasyslab: geospark-sql_2.3:1.2.0
[error]   Not found
[error]   Not found
[error]   not found: /home/gmandi/.ivy2/local/org.datasyslab/ geospark-sql_2.3/1.2.0/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://repo1.maven.org/maven2/org/datasyslab/ geospark-sql_2.3/1.2.0/ geospark-sql_2.3-1.2.0.pom (Server returned HTTP response code: 400 for URL: https://repo1.maven.org/maven2/org/datasyslab/ geospark-sql_2.3/1.2.0/ geospark-sql_2.3-1.2.0.pom) while downloading https://repo1.maven.org/maven2/org/datasyslab/ geospark-sql_2.3/1.2.0/ geospark-sql_2.3-1.2.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:246)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:215)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:215)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2947)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading org.datasyslab: geospark-sql_2.3:1.2.0
[error]   Not found
[error]   Not found
[error]   not found: /home/gmandi/.ivy2/local/org.datasyslab/ geospark-sql_2.3/1.2.0/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://repo1.maven.org/maven2/org/datasyslab/ geospark-sql_2.3/1.2.0/ geospark-sql_2.3-1.2.0.pom (Server returned HTTP response code: 400 for URL: https://repo1.maven.org/maven2/org/datasyslab/ geospark-sql_2.3/1.2.0/ geospark-sql_2.3-1.2.0.pom) while downloading https://repo1.maven.org/maven2/org/datasyslab/ geospark-sql_2.3/1.2.0/ geospark-sql_2.3-1.2.0.pom
